name: CI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov torch torchvision torchaudio gymnasium pixyz
          pip install -e .

      - name: Run tests
        run: pytest --doctest-modules --cov=pixyzrl --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov-report=xml pixyzrl | tee coverage.xml

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./coverage.xml
          junitxml-path: ./pytest.xml

      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
        with:
          token: 3095d231-c0f1-4412-b2f7-d2c9e620288e
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
