name: generate_pdoc

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate_pdoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pdoc3
          pip install -e .

      - name: Generate documentation
        run: |
          pdoc --html --output-dir docs pixyzrl

      - name: Pull latest changes
        run: git pull origin feature/pages

      - name: Commit and push changes
        run: |
          git add docs/
          git commit -m "Update documentation"
          git push origin feature/pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
