name: generate_pdoc

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate_pdoc:
    name: generating pdoc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Python をセットアップ
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # 必要な依存関係をインストール
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pdoc
          pip install -e .

      # pdoc を実行してドキュメントを生成
      - name: Generate Documentation with pdoc
        run: pdoc --html -o docs --force main.py

      # 変更があれば push する
      - name: Push new docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}

          if git diff --quiet; then
            echo "No changes to commit"
          else
            git add docs/
            git commit -m "Generating docs via GitHub Actions"
            git push origin main  # ✅ プルリクの refs/pull/... ではなく main に push
          fi
